### ISSUE TITLE
[ Future request ] running datapack without pasting actual file

### ISSUE THREAD

**Issue by JackYevhen** [Jaffe2718/Socket-Injection-Debugger#11]
Button, witch lets you create a `shadow datapack` (mod must trick minecraft into thinking datapack is there, when in fact the files are in your project, not in `datapacks` folder), so you don't have to search for the world folder and paste the files there.

**Comment by Jaffe2718** [comment]
Do you mean that you can automatically paste the generated packets inside the world folder of a running Minecraft instance?

**Comment by Jaffe2718** [comment]
Try these:
[mod-3.0.0-rc.1-plugin-1.3.0-rc.1.zip](https://github.com/Jaffe2718/Command-Debug-DevKit/files/13266773/mod-3.0.0-rc.1-plugin-1.3.0-rc.1.zip)

**Comment by JackYevhen** [comment]
I know you want look at it, so im duplicating it here: `I mean add just default world in minecraft by mod, and not in IntelIJ`.

**Comment by Jaffe2718** [comment]
I don't seem to understand your requirements, can you describe the workflow of the functions you need in more detail?

**Comment by Jaffe2718** [comment]
Do you mean that the world of running Minecraft instances can reference datapack files outside of Minecraft application stubs through mod? Techniques like using virtual files?

**Comment by JackYevhen** [comment]
> I know you want look at it, so im duplicating it here: `I mean add just default world in minecraft by mod, and not in IntelIJ`.

I said it here, because you closed another issue, because you thought I want to run Minecraft from IntelIJ, but I mean just add world with default settings, witch auto-deletes after you exit.

What's about this:

> Do you mean that the world of running Minecraft instances can reference datapack files outside of Minecraft application stubs through mod? Techniques like using virtual files?

I am not familiar with `"virtual files"` but `"...reference datapack files outside of Minecraft application..."` perfectly means what I thought of (sorry, if its impossible).

**Comment by Jaffe2718** [comment]
I probably understand your requirements, that is, to introduce the following two series operations of datapack: 
1. Import and delete series operations of ordinary datapack. 
2. Connect packets, which are equivalent to importing and managing datapack in the form of temporary files or virtual files. These connections will be invalidated after the game exits. The file body of the package does not remain inside the archive of the Minecraft application.

These functions are complicated, and it may take me a while to finish them.

**Comment by Jaffe2718** [comment]
Try this https://github.com/Jaffe2718/Command-Debug-DevKit/releases/tag/p-1.3.0-rc.2

**Comment by Jaffe2718** [comment]
Well, I think you can use the stable version of the mod and plugin https://github.com/Jaffe2718/Command-Debug-DevKit/releases/tag/p-1.3.0
