### ISSUE TITLE
Add Color Scheme settings for Minecraft function files.

### ISSUE THREAD

**Issue by Ayfri** [Jaffe2718/Socket-Injection-Debugger#2]
This will let us be able to customize the style of each different tokens, it can be very useful. Especially for people customizing a lot of tokens so that each one has a different style, so it's very easy to differentiate between them.

**Comment by Jaffe2718** [comment]
Well ~
Customize syntax hight lighting is indeed a large project, with this amount of work need to do. Maybe I will add such these features in plugin `1.1.x` as a big update.

**Comment by Ayfri** [comment]
No problem, it's just a suggestion, take the time to need to develop what you want before that, It's not in a hurry !

**Comment by Jaffe2718** [comment]
For further information, you can visit and open a new issues at [![CustomSyntaxHighlightingColorSetting](https://img.shields.io/badge/Milestone-Custom%20Syntax%20Highlighting%20Color%20Setting-00FFFF.svg)](https://github.com/Jaffe2718/Command-Debug-DevKit/milestone/1)

**Comment by Jaffe2718** [comment]
use #3 in [![CustomSyntaxHighlightingColorSetting](https://img.shields.io/badge/Milestone-Custom%20Syntax%20Highlighting%20Color%20Setting-00FFFF.svg)](https://github.com/Jaffe2718/Command-Debug-DevKit/milestone/1) or ceate other issues at [![CustomSyntaxHighlightingColorSetting](https://img.shields.io/badge/Milestone-Custom%20Syntax%20Highlighting%20Color%20Setting-00FFFF.svg)](https://github.com/Jaffe2718/Command-Debug-DevKit/milestone/1)
