### ISSUE TITLE
[BUG]: Having the plugin activated writes three `"` when typing one instead of two.

### ISSUE THREAD

**Issue by Ayfri** [Jaffe2718/Socket-Injection-Debugger#5]
Hello, when I have the plugin activated, if I type one `"`, I get three instead of two. Regardless of the language I am writing in.

**Comment by Jaffe2718** [comment]
I see that, try this [1.1.1-rc1](https://github.com/Jaffe2718/Command-Debug-DevKit/files/12655181/idea-plugin.zip).

**Comment by Ayfri** [comment]
Yup, it looks like it's fixed!

**Comment by Jaffe2718** [comment]
Great, so I may release the stable version of `1.1.1` plugin in the next two days.
