### ISSUE TITLE
Functions can now contain macro lines, making them Function Macros

### ISSUE THREAD

**Issue by Jaffe2718** [Jaffe2718/Socket-Injection-Debugger#7]
- Any line beginning with `$` (as the first non-space character) marks a macro line.
- A macro line also contains one or more substitutions in the form of `$(variable)`.
    - Commands with variable subsitutions will be re-evaluated after substitution.
        - Running commands with this type have extra cost compared to pre-parsed functions.
        - Game will attempt to cache the result of certain parameter set being used in a call, to reduce costs when repeatedly calling.
- When calling a function macro a compound with data for all argument variables must be provided.

**Comment by Jaffe2718** [comment]
Test plugin [1.1.2-rc1](https://github.com/Jaffe2718/Command-Debug-DevKit/files/12705717/idea-plugin.zip).

**Comment by Ayfri** [comment]
![image](https://github.com/Jaffe2718/Command-Debug-DevKit/assets/34159136/50efc032-49c8-4b14-b4ed-23d9225bea3b)
Doesn't seem to be	working well using 1.1.2 release.

**Comment by Jaffe2718** [comment]
So far, this is just an experimental feature. I'm not familiar with macro syntax yet, and it may take a long time to perfect this feature.

**Comment by Jaffe2718** [comment]
> ![image](https://user-images.githubusercontent.com/34159136/270803115-50efc032-49c8-4b14-b4ed-23d9225bea3b.png) Doesn't seem to be working well using 1.1.2 release.

Try [1.2.0-rc5](https://github.com/Jaffe2718/Command-Debug-DevKit/files/12737756/idea-plugin.zip)

**Comment by Jaffe2718** [comment]
It seems that version 1.2.0-rc5 has a bug in the plugin's ability to create projects that prevents the creation of packet projects.
Try this one [1.2.0-rc6](https://github.com/Jaffe2718/Command-Debug-DevKit/files/12740771/idea-plugin.zip)

**Comment by Ayfri** [comment]
It's now working almost as expected, I'm still getting an error though:
![image](https://github.com/Jaffe2718/Command-Debug-DevKit/assets/34159136/18188728-9dd6-4a3f-8bb8-812475516843)

**Comment by Jaffe2718** [comment]
> It's now working almost as expected, I'm still getting an error though: ![image](https://user-images.githubusercontent.com/34159136/271071057-18188728-9dd6-4a3f-8bb8-812475516843.png)


[1.2.0-rc7](https://github.com/Jaffe2718/Command-Debug-DevKit/files/12745406/idea-plugin.zip)

**Comment by Ayfri** [comment]
![image](https://github.com/Jaffe2718/Command-Debug-DevKit/assets/34159136/79544e37-7256-492f-af69-103cea1dc96e)
Working as expected !

Maybe for a more complex feature that can be made far in the future, you could add navigation from the macro to the commands calling the current function with the arguments as a JSON object.
For example, my screen is on the `function1.mcfunction`, in the `function2.mcfunction` I have this code:
```mcfunction
function datapack:function1 {my_macro: "test"}
```
When CTRL clicking (or CTRL B) to `$(my_macro)`, the `function2.mcfunction` file on the first line would be listed as the usage of the macro.

**Comment by Jaffe2718** [comment]
There are some details of the syntax that I need to test, for example:
```mcfunction
say hello \
 world

say try to send \\
```
I need to adjust these details to match the actual results of the program.

**Comment by Jaffe2718** [comment]
https://github.com/Jaffe2718/Command-Debug-DevKit/releases/tag/p-1.2.0
